package rs.ac.bg.fon.CinemaClient.forms;

import java.awt.event.ActionListener;

import javax.swing.JTable;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.SwingConstants;

/**
 *
 * @author Nikola
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        setTitle("Cinema administration system");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTopMovies = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFilm = new javax.swing.JMenu();
        miFilmCreate = new javax.swing.JMenuItem();
        miFilmSearch = new javax.swing.JMenuItem();
        miFilmDelete = new javax.swing.JMenuItem();
        jMenuTerm = new javax.swing.JMenu();
        miTermCreate = new javax.swing.JMenuItem();
        miTermSearch = new javax.swing.JMenuItem();
        miTermEdit = new javax.swing.JMenuItem();
        miTermDelete = new javax.swing.JMenuItem();
        jMenuReservation = new javax.swing.JMenu();
        miReservationCreate = new javax.swing.JMenuItem();
        miReservationDelete = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("IMDb Top 10 Movies");

        tblTopMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTopMovies);

        jMenuFilm.setText("Film");

        miFilmCreate.setText("Create");
        jMenuFilm.add(miFilmCreate);

        miFilmSearch.setText("Search");
        jMenuFilm.add(miFilmSearch);

        miFilmDelete.setText("Delete");
        jMenuFilm.add(miFilmDelete);

        jMenuBar1.add(jMenuFilm);

        jMenuTerm.setText("Term");

        miTermCreate.setText("Create");
        jMenuTerm.add(miTermCreate);

        miTermSearch.setText("Search");
        jMenuTerm.add(miTermSearch);

        miTermEdit.setText("Edit");
        jMenuTerm.add(miTermEdit);

        miTermDelete.setText("Delete");
        jMenuTerm.add(miTermDelete);

        jMenuBar1.add(jMenuTerm);

        jMenuReservation.setText("Reservation");

        miReservationCreate.setText("Create");
        jMenuReservation.add(miReservationCreate);

        miReservationDelete.setText("Delete");
        jMenuReservation.add(miReservationDelete);

        jMenuBar1.add(jMenuReservation);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(40)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 676, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblTitle))
        			.addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(40)
        			.addComponent(lblTitle)
        			.addGap(30)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(68, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFilm;
    private javax.swing.JMenu jMenuReservation;
    private javax.swing.JMenu jMenuTerm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JMenuItem miFilmCreate;
    private javax.swing.JMenuItem miFilmDelete;
    private javax.swing.JMenuItem miFilmSearch;
    private javax.swing.JMenuItem miReservationCreate;
    private javax.swing.JMenuItem miReservationDelete;
    private javax.swing.JMenuItem miTermCreate;
    private javax.swing.JMenuItem miTermDelete;
    private javax.swing.JMenuItem miTermEdit;
    private javax.swing.JMenuItem miTermSearch;
    private javax.swing.JTable tblTopMovies;
    // End of variables declaration                   
    
    public void miFilmCreateAddActionListener(ActionListener actionListener){
        miFilmCreate.addActionListener(actionListener);
    }
    
    public void miTermCreateAddActionListener(ActionListener actionListener){
        miTermCreate.addActionListener(actionListener);
    }
    
    public void miFilmSearchAddActionListener(ActionListener actionListener){
        miFilmSearch.addActionListener(actionListener);
    }
    public void miTermSearchAddActionListener(ActionListener actionListener){
        miTermSearch.addActionListener(actionListener);
    }
    
    public void miReservationCreateAddActionListener(ActionListener actionListener){
        miReservationCreate.addActionListener(actionListener);
    }
    public void miReservationDeleteAddActionListener(ActionListener actionListener){
        miReservationDelete.addActionListener(actionListener);
    }
    public void miFilmDeleteAddActionListener(ActionListener actionListener){
        miFilmDelete.addActionListener(actionListener);
    }
    public void miTermEditAddActionListener(ActionListener actionListener){
        miTermEdit.addActionListener(actionListener);
    }
    public void miTermDeleteAddActionListener(ActionListener actionListener){
        miTermDelete.addActionListener(actionListener);
    }

    public JTable getTblTopMovies() {
        return tblTopMovies;
    }

    public void setTblTopMovies(JTable tblTopMovies) {
        this.tblTopMovies = tblTopMovies;
    }
}