package rs.ac.bg.fon.CinemaClient.forms;

import java.awt.event.ActionListener;

/**
 *
 * @author Nikola
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        setTitle("Cinema administration system");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFilm = new javax.swing.JMenu();
        miFilmCreate = new javax.swing.JMenuItem();
        miFilmSearch = new javax.swing.JMenuItem();
        miFilmDelete = new javax.swing.JMenuItem();
        jMenuTerm = new javax.swing.JMenu();
        miTermCreate = new javax.swing.JMenuItem();
        miTermSearch = new javax.swing.JMenuItem();
        miTermEdit = new javax.swing.JMenuItem();
        miTermDelete = new javax.swing.JMenuItem();
        jMenuReservation = new javax.swing.JMenu();
        miReservationCreate = new javax.swing.JMenuItem();
        miReservationDelete = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuFilm.setText("Film");

        miFilmCreate.setText("Create");
        jMenuFilm.add(miFilmCreate);

        miFilmSearch.setText("Search");
        jMenuFilm.add(miFilmSearch);

        miFilmDelete.setText("Delete");
        jMenuFilm.add(miFilmDelete);

        jMenuBar1.add(jMenuFilm);

        jMenuTerm.setText("Term");

        miTermCreate.setText("Create");
        jMenuTerm.add(miTermCreate);

        miTermSearch.setText("Search");
        jMenuTerm.add(miTermSearch);

        miTermEdit.setText("Edit");
        jMenuTerm.add(miTermEdit);

        miTermDelete.setText("Delete");
        jMenuTerm.add(miTermDelete);

        jMenuBar1.add(jMenuTerm);

        jMenuReservation.setText("Reservation");

        miReservationCreate.setText("Create");
        jMenuReservation.add(miReservationCreate);

        miReservationDelete.setText("Delete");
        jMenuReservation.add(miReservationDelete);

        jMenuBar1.add(jMenuReservation);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFilm;
    private javax.swing.JMenu jMenuReservation;
    private javax.swing.JMenu jMenuTerm;
    private javax.swing.JMenuItem miFilmCreate;
    private javax.swing.JMenuItem miFilmDelete;
    private javax.swing.JMenuItem miFilmSearch;
    private javax.swing.JMenuItem miReservationCreate;
    private javax.swing.JMenuItem miReservationDelete;
    private javax.swing.JMenuItem miTermCreate;
    private javax.swing.JMenuItem miTermDelete;
    private javax.swing.JMenuItem miTermEdit;
    private javax.swing.JMenuItem miTermSearch;
    // End of variables declaration                   

    public void miFilmCreateAddActionListener(ActionListener actionListener){
        miFilmCreate.addActionListener(actionListener);
    }
    
    public void miTermCreateAddActionListener(ActionListener actionListener){
        miTermCreate.addActionListener(actionListener);
    }
    
    public void miFilmSearchAddActionListener(ActionListener actionListener){
        miFilmSearch.addActionListener(actionListener);
    }
    public void miTermSearchAddActionListener(ActionListener actionListener){
        miTermSearch.addActionListener(actionListener);
    }
    
    public void miReservationCreateAddActionListener(ActionListener actionListener){
        miReservationCreate.addActionListener(actionListener);
    }
    public void miReservationDeleteAddActionListener(ActionListener actionListener){
        miReservationDelete.addActionListener(actionListener);
    }
    public void miFilmDeleteAddActionListener(ActionListener actionListener){
        miFilmDelete.addActionListener(actionListener);
    }
    public void miTermEditAddActionListener(ActionListener actionListener){
        miTermEdit.addActionListener(actionListener);
    }
    public void miTermDeleteAddActionListener(ActionListener actionListener){
        miTermDelete.addActionListener(actionListener);
    }
}

