package rs.ac.bg.fon.CinemaClient.forms;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Nikola
 */
public class FrmTermCreate extends javax.swing.JDialog {

    /**
     * Creates new form FrmTermCreate
     */
    public FrmTermCreate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Term Create");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        groupType = new javax.swing.ButtonGroup();
        lblFilm = new javax.swing.JLabel();
        cbFilm = new javax.swing.JComboBox<>();
        lblHall = new javax.swing.JLabel();
        cbHall = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        lblProjectionType = new javax.swing.JLabel();
        rb3D = new javax.swing.JRadioButton();
        rb2D = new javax.swing.JRadioButton();
        btnAddTerm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblFilm.setText("Film:");

        lblHall.setText("Hall:");

        lblDate.setText("Date & Time:");

        lblProjectionType.setText("Projection Type:");

        groupType.add(rb3D);
        rb3D.setText("3D");

        groupType.add(rb2D);
        rb2D.setText("2D");

        btnAddTerm.setText("Add term");

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFilm)
                    .addComponent(lblHall)
                    .addComponent(lblDate)
                    .addComponent(lblProjectionType))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb3D)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb2D))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDate)
                                .addComponent(cbFilm, 0, 282, Short.MAX_VALUE)
                                .addComponent(cbHall, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddTerm)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilm)
                    .addComponent(cbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHall)
                    .addComponent(cbHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProjectionType)
                    .addComponent(rb3D)
                    .addComponent(rb2D))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnAddTerm))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAddTerm;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<Object> cbFilm;
    private javax.swing.JComboBox<Object> cbHall;
    private javax.swing.ButtonGroup groupType;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFilm;
    private javax.swing.JLabel lblHall;
    private javax.swing.JLabel lblProjectionType;
    private javax.swing.JRadioButton rb2D;
    private javax.swing.JRadioButton rb3D;
    private javax.swing.JTextField txtDate;
    // End of variables declaration                   

   

    public JRadioButton getRb2D() {
        return rb2D;
    }

    public JRadioButton getRb3D() {
        return rb3D;
    }

    public JTextField getTxtDate() {
        return txtDate;
    }

    public void btnAddTermAddActionListener(ActionListener actionListener){
        btnAddTerm.addActionListener(actionListener);
    }
    public void btnCancelAddActionListener(ActionListener actionListener){
        btnCancel.addActionListener(actionListener);
    }

    public JComboBox<Object> getCbFilm() {
        return cbFilm;
    }

    public JComboBox<Object> getCbHall() {
        return cbHall;
    }
    
    
}

